PREFIX vidp: <https://bmake.th-brandenburg.de/vidp/>
PREFIX schema: <https://schema.org/>
PREFIX vide: <https://bmake.th-brandenburg.de/vide/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?iri ?headline ?name ?description ?about ?thumbnail ?url
WHERE {
 VALUES ?iri { vide:%videoLecture% }
 ?iri a vidp:VideoLecture ;
        schema:headline ?headline ;
        schema:name ?name ;
        schema:description ?description ;
        schema:about ?about ;
        schema:thumbnail ?t ;
        schema:url ?url .
 ?t schema:name ?thumbnail .
 FILTER ( lang(?headline) = "%language%" )
 FILTER ( lang(?description) = "%language%" )
}